const products = [
  {
    id: 1,
    name: 'Vestido Floral Verão',
    brand: 'MODEXA',
    price: 89.90,
    old: 149.90,
    badge: 'Sale',
    colors: ['#f5c4b3', '#aaf0cb', '#b5d4f4'],
    sizes: ['P', 'M', 'G'],
    category: 'Feminino',
    description: 'Um vestido leve, fluido e romântico. Com estampa floral delicada e caimento perfeito, é a escolha ideal para dias quentes e ensolarados, proporcionando conforto absoluto e elegância sutil.',
    img: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=400&q=80'
  },
  {
    id: 2,
    name: 'Blusa Cropped Linho',
    brand: 'MODEXA',
    price: 49.90,
    old: null,
    badge: 'New',
    colors: ['#fff', '#2c2c2a', '#c4705a'],
    sizes: ['P', 'M', 'G', 'GG'],
    category: 'Feminino',
    description: 'Desenvolvido em linho nobre, este cropped traz um ar sofisticado e natural. O caimento estruturado e o abotoamento traseiro oferecem versatilidade para composições casuais ou refinadas.',
    img: 'https://images.unsplash.com/photo-1594938298603-c8148c4b4b4e?w=400&q=80'
  },
  {
    id: 3,
    name: 'Calça Wide Leg Jeans',
    brand: 'MODEXA',
    price: 129.90,
    old: 199.90,
    badge: 'Hot',
    colors: ['#6080a0', '#2c2c2a', '#f5e6e0'],
    sizes: ['36', '38', '40', '42', '44'],
    category: 'Feminino',
    description: 'A calça queridinha do momento. Modelagem de cintura alta, corte reto amplo e lavagem clássica que valoriza o corpo. Confortável e estilosa, ideal para um visual moderno do dia à noite.',
    img: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=400&q=80'
  },
  {
    id: 4,
    name: 'Conjunto Alfaiataria',
    brand: 'MODEXA',
    price: 199.90,
    old: 299.90,
    badge: 'Sale',
    colors: ['#f5ece8', '#2c2c2a', '#80a080'],
    sizes: ['P', 'M', 'G'],
    category: 'Feminino',
    description: 'Elegância instantânea. Conjunto composto por blazer acinturado e calça reta com pregas. Tecido encorpado que não amassa facilmente, perfeito para o ambiente profissional ou eventos especiais.',
    img: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=400&q=80'
  },
  {
    id: 5,
    name: 'Saia Midi Plissada',
    brand: 'MODEXA',
    price: 79.90,
    old: 119.90,
    badge: 'Sale',
    colors: ['#c4705a', '#f5c4b3', '#2c2c2a'],
    sizes: ['P', 'M', 'G'],
    category: 'Feminino',
    description: 'Uma saia com movimento incrível. Plissado de alta durabilidade com elástico na cintura para ajuste confortável. A cor terrosa traz personalidade para combinações com salto ou tênis.',
    img: 'https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=400&q=80'
  },
  {
    id: 6,
    name: 'Camiseta Oversized',
    brand: 'MODEXA',
    price: 39.90,
    old: null,
    badge: 'New',
    colors: ['#fff', '#888', '#f5e6e0'],
    sizes: ['P', 'M', 'G', 'GG'],
    category: 'Masculino',
    description: 'Conforto urbano definitivo. Modelagem oversized com ombros caídos e malha 100% algodão de alta gramatura. Durabilidade impecável e toque ultra macio para uso diário.',
    img: 'https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=400&q=80'
  },
  {
    id: 7,
    name: 'Vestido Slip Cetim',
    brand: 'MODEXA',
    price: 159.90,
    old: 229.90,
    badge: 'Hot',
    colors: ['#c4705a', '#f5c4b3', '#2c2c2a'],
    sizes: ['P', 'M', 'G'],
    category: 'Feminino',
    description: 'Minimalismo chique dos anos 90 redefinido. Confeccionado em cetim com brilho sutil, caimento enviesado que contorna a silhueta e alças finas reguláveis. Um clássico irresistível.',
    img: 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=400&q=80'
  },
  {
    id: 8,
    name: 'Blazer Oversized',
    brand: 'MODEXA',
    price: 189.90,
    old: 269.90,
    badge: 'Sale',
    colors: ['#2c2c2a', '#888', '#c4705a'],
    sizes: ['P', 'M', 'G', 'GG'],
    category: 'Masculino',
    description: 'Alfaiataria moderna com corte solto e despojado. Estruturado com ombreiras sutis e lapela clássica. Uma peça coringa para adicionar atitude instantânea a qualquer composição.',
    img: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?w=400&q=80'
  }
];